# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks

namespace :rabbitmq do
  desc "Setup routing"
  task :setup do
    require "bunny"

    conn = Bunny.new
    conn.start

    ch = conn.create_channel

    x = ch.fanout("blog.posts")

    queue = ch.queue("dashboard.posts", durable: true)

    queue.bind("blog.posts")

    conn.close
  end
end
